# PostToolUse hook generated by rulesync — edit .rulesync/hooks.jsonc and regenerate.
# rulesync-owned: cline-hooks

if ($null -ne $IsWindows -and -not $IsWindows) {
  Write-Output '{"cancel": false, "contextModification": "", "errorMessage": ""}'
  exit 0
}

$payload = [Console]::In.ReadToEnd()
$cancel = $false
$errorMessage = ''

if (-not $cancel) {
  $hookStderr = ($payload | & cmd /c 'if [ -f task_plan.md ] || [ -f .planning/.active_plan ] || ls .planning/*/task_plan.md >/dev/null 2>&1; then echo ''[planning-with-files] Update progress.md with what you just did. If a phase is now complete, update task_plan.md status.''; fi' 2>&1 | Out-String)
  $hookStatus = $LASTEXITCODE
  if ($hookStatus -eq 2) {
    $cancel = $true
    $errorMessage = $hookStderr
  } elseif ($hookStatus -ne 0) {
    Write-Error 'rulesync PostToolUse hook failed'
    $errorMessage = $hookStderr
  }
}

@{
  cancel = $cancel
  contextModification = ""
  errorMessage = $errorMessage
} | ConvertTo-Json -Compress
