# PreCompact hook generated by rulesync — edit .rulesync/hooks.jsonc and regenerate.
# rulesync-owned: cline-hooks

if ($null -ne $IsWindows -and -not $IsWindows) {
  Write-Output '{"cancel": false, "contextModification": "", "errorMessage": ""}'
  exit 0
}

$payload = [Console]::In.ReadToEnd()
$cancel = $false
$errorMessage = ''

if (-not $cancel) {
  $hookStderr = ($payload | & cmd /c 'SH=$(ls .claude/skills/planning-with-files/scripts/inject-plan.sh "$HOME/.claude/skills/planning-with-files/scripts/inject-plan.sh" "$HOME/.agents/skills/planning-with-files/scripts/inject-plan.sh" 2>/dev/null | head -1); [ -n "$SH" ] && sh "$SH" --context=precompact; exit 0' 2>&1 | Out-String)
  $hookStatus = $LASTEXITCODE
  if ($hookStatus -eq 2) {
    $cancel = $true
    $errorMessage = $hookStderr
  } elseif ($hookStatus -ne 0) {
    Write-Error 'rulesync PreCompact hook failed'
    $errorMessage = $hookStderr
  }
}

@{
  cancel = $cancel
  contextModification = ""
  errorMessage = $errorMessage
} | ConvertTo-Json -Compress
