# PreToolUse hook generated by rulesync — edit .rulesync/hooks.jsonc and regenerate.
# rulesync-owned: cline-hooks

if ($null -ne $IsWindows -and -not $IsWindows) {
  Write-Output '{"cancel": false, "contextModification": "", "errorMessage": ""}'
  exit 0
}

$payload = [Console]::In.ReadToEnd()
$cancel = $false
$errorMessage = ''

if (-not $cancel) {
  $hookStderr = ($payload | & cmd /c 'node .rulesync/hooks/deny-secret-in-write.mjs' 2>&1 | Out-String)
  $hookStatus = $LASTEXITCODE
  if ($hookStatus -eq 2) {
    $cancel = $true
    $errorMessage = $hookStderr
  } elseif ($hookStatus -ne 0) {
    Write-Error 'rulesync PreToolUse hook failed'
    $errorMessage = $hookStderr
  }
}

@{
  cancel = $cancel
  contextModification = ""
  errorMessage = $errorMessage
} | ConvertTo-Json -Compress
